name: Publish New Version

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Asciidoctor
      run: ./gradlew asciidoctor
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: ./build/asciidoc/html5
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}  
